export const dkgray = '#5c5c5c'
export const white = '#fff'
export const orange = '#f89B36'
export const red = '#fb4539'
export const magenta = '#8d295B'
export const green = '#365B36'
export const ltgreen = '#afcac4'
export const gray = '#e4e7ea'
